# Generated by Django 2.2 on 2019-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Patient'),
        ),
        migrations.AlterField(
            model_name='freetimings',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Doctor'),
        ),
        migrations.AlterField(
            model_name='freetimings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
