# Generated by Django 2.2 on 2019-11-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='username',
        ),
    ]
