# Generated by Django 2.2 on 2019-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('did', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
