# Generated by Django 2.2 on 2019-11-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Patient')),
            ],
        ),
    ]
