# Generated by Django 2.2 on 2019-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20191111_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTimings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('did', models.IntegerField()),
                ('t0_1', models.BooleanField()),
                ('t1_2', models.BooleanField()),
                ('t2_3', models.BooleanField()),
                ('t3_4', models.BooleanField()),
                ('t4_5', models.BooleanField()),
                ('t5_6', models.BooleanField()),
                ('t6_7', models.BooleanField()),
                ('t7_8', models.BooleanField()),
                ('t8_9', models.BooleanField()),
                ('t9_10', models.BooleanField()),
                ('t10_11', models.BooleanField()),
                ('t11_12', models.BooleanField()),
                ('t12_13', models.BooleanField()),
                ('t13_14', models.BooleanField()),
                ('t14_15', models.BooleanField()),
                ('t15_16', models.BooleanField()),
                ('t16_17', models.BooleanField()),
                ('t17_18', models.BooleanField()),
                ('t18_19', models.BooleanField()),
                ('t19_20', models.BooleanField()),
                ('t20_21', models.BooleanField()),
                ('t21_22', models.BooleanField()),
                ('t22_23', models.BooleanField()),
                ('t23_24', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
